/*
 * msg_kind.h
 *
 *  Created on: Mar 24, 2024
 *      Author: cotti
 */

#ifndef MSG_KIND_H_
#define MSG_KIND_H_

enum MsgKind_t {
    MD_DATA_REQUEST,
    MD_DATA_INDICATION,

    MLME_ASSOCIATE_REQUEST,
    MLME_ASSOCIATE_CONFIRM,
    MLME_ASSOCIATE_INDICATION,
    MLME_ASSOCIATE_RESPONSE,

    MLME_DISASSOCIATE_REQUEST,
    MLME_DISASSOCIATE_CONFIRM,
    MLME_DISASSOCIATE_INDICATION,

    MLME_GET_REQUEST,
    MLME_GET_CONFIRM,

    MLME_SET_REQUEST,
    MLME_SET_CONFIRM,

    MLME_SCAN_REQUEST,
    MLME_SCAN_CONFIRM,

    MLME_START_REQUEST,
    MLME_START_CONFIRM,

    MLME_STOP_REQUEST,
    MLME_STOP_CONFIRM
};



#endif /* MSG_KIND_H_ */
